; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

;@Ahk2Exe-UpdateManifest 2
;@Ahk2Exe-SetMainIcon Libs\Icons\uninstaller.ico
;// RunAsAmin()

#Include, Libs\DFChrome

; ************* [ INITIALIZE ] ***************

FileRead, configs_, manifest.json
CONFIGS := chrome.Jxon_Load(configs_)

df_TxtAppName := CONFIGS.app.name
df_packageName := StrReplace(CONFIGS.app.package_name, " ")
df_TxtAppName := CONFIGS.app.name

; ************* [ WINDOW ] ***************

Menu Tray, Icon, shell32.dll, 102

Gui -MinimizeBox -MaximizeBox +AlwaysOnTop
Gui Color, White
Gui Add, Progress, hWndhPrg vPrg x24 y88 w467 h33 -Smooth, 0
Gui Font, Bold cRed
Gui Add, Button, hWndhBtnOuiDesinstaller vBtnOuiDesinstaller gDesinstaller x24 y145 w188 h31, &OUI DÉSINSTALLER
Gui Font
Gui Add, Button, hWndhBtnNon vBtnNon gCancelAction x304 y144 w190 h34, &NON
Gui Font, s14
Gui Add, Text, x24 y8 w118 h45 +0x200, Désinstaller 
Gui Font
Gui Font, s11 cTeal
Gui Add, Text, vTxtAppName x24 y48 w318 h23 +0x200, App name
Gui Font

GuiControl,, TxtAppName, %df_TxtAppName%

Gui Show, w524 h189, DESINSTALLATION
Return

; ************* [ EVENTS fn ] ***************

Desinstaller(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
    global df_TxtAppName

    GuiControl, Disable, BtnNon
    GuiControl, Disable, BtnOuiDesinstaller
    GuiControl,, Prg, 40
    ; REMOVE DIRECTORY
    FileRemoveDir, %A_WorkingDir%, 1 ; * Remove current working directory
    FileRemoveDir, %A_Programs%\%df_TxtAppName%, 1 ; * Remove from start Menu
    FileDelete, %A_Desktop%\%df_TxtAppName%.lnk ; * Remove desktop Shortcut (.lnk)
    Sleep, 2000 ; 2Secs
    GuiControl,, Prg, 100
    Sleep, 1000 ; 2Secs

    Gosub, GuiClose
}

RunAsAmin() {
    full_command_line := DllCall("GetCommandLine", "str")

    if not (A_IsAdmin or RegExMatch(full_command_line, " /restart(?!\S)")) {
        try
        {
            if A_IsCompiled
                Run *RunAs "%A_ScriptFullPath%" /restart
            else
                Run *RunAs "%A_AhkPath%" /restart "%A_ScriptFullPath%"
        }
        Gosub, GuiClose
    }
}

CancelAction(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
    Gosub, GuiClose
}

; ************* [ CLOSE CONTROL ] **************

GuiEscape:
GuiClose:
    ExitApp
